---
- name: Install pip packages.
  pip:
    name:
      - flask
      - gunicorn
    executable: /usr/bin/pip3

- name: Clone a repo from git
  git:
    repo: https://github.com/jihyungSong/devops-course-sample.git
    dest: /root/devops-course-sample

- name: Copy flask source for execute
  copy:
    src: /root/devops-course-sample/flask/src/
    dest: /opt/flask

- name: Create Gunicorn config file from template
  template:
    src: gunicorn.cfg.py.template
    dest: /etc/gunicorn.cfg.py
    owner: root
    group: root
    mode: 0644
  notify: Restart Gunicorn

- name: Install systemd service configuration
  template:
    src: systemd.conf.template
    dest: /etc/systemd/system/gunicorn.service.d
    mode: 0755
  notify: Restart gunicorn
  when: ansible_service_mgr == "systemd"

- name: Enable gunicorn service
  service:
    name: gunicorn
    enabled: yes