---
- name: Install pip packages.
  pip:
    name:
      - flask
      - gunicorn
    executable: /usr/bin/pip3

- name: Clone a repo from git
  git:
    repo: https://github.com/jihyungSong/devops-course-sample.git
    dest: /root/devops-course-sample

- name: Copy flask source for execute
  copy:
    src: /root/devops-course-sample/flask/src/
    dest: /opt/flask

- name: Create gunicorn user
  user:
    name: gunicorn
    state: present

- name: Create Gunicorn config file from template
  template:
    src: gunicorn.cfg.py.template
    dest: /etc/gunicorn.cfg.py
  notify:
    - restart gunicorn

- name: Configure systemd service
  template:
    src: systemd.conf.template
    dest: /etc/systemd/system/gunicorn.service
  notify:
    - reload daemon
    - restart gunicorn
  when: ansible_service_mgr == "systemd"

- name: Enable gunicorn service
  service:
    name: gunicorn
    enabled: yes