---
- name: Install pip packages.
  pip:
    name:
      - flask
      - gunicorn
    executable: /usr/bin/pip3

- name: Clone a repo from git
  git:
    repo: https://github.com/jihyungSong/devops-course-sample.git
    dest: /root/devops-course-sample

- name: Copy flask source for execute
  copy:
    src: /root/devops-course-sample/flask/src/
    dest: /opt/flask

- name: Create Gunicorn config file from template
  template:
    src: gunicorn.cfg.py.template
    dest: /etc/gunicorn.cfg.py
    owner: root
    group: root
    mode: 0644

- name: Run Gunicorn with flask
  gunicorn:
    app: 'wsgi:app'
    chdir: /opt/flask
    config: /etc/gunicorn.cfg.py

