---
- name: Install pip packages.
  pip:
    name:
      - flask
      - gunicorn
    executable: /usr/bin/pip3

- name: Clone a repo from git
  git:
    repo: https://github.com/jihyungSong/devops-course-sample.git
    dest: /root/devops-course-sample

- name: Copy flask source for execute
  copy:
    src: /root/devops-course-sample/flask/src/
    dest: /opt/flask

- name: Execute Setup
  pip:
    name: .
    executable: /usr/bin/pip3
    chdir: /opt/flask

- name: Run Gunicorn with flask
  gunicorn:
    app: 'wsgi:app'
    chdir: /opt/flask
