---
bind_addr: '0.0.0.0'
gunicorn_port: '5000'
backlog: 2048
worker: 1
worker_class: 'sync'
worker_connections: 1000
gunicorn_timeout: 30
keepalive: 2
daemon_enabled: True
pidfile: '/proc/gunicorn'
error_log: '/var/log/error-gunicorn.log'
log_level: 'info'
access_log: '/var/log/access-gunicorn.log'
