apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
  namespace: devops
spec:
  containers:
  - name: nginx
    image: 574261620507.dkr.ecr.us-east-1.amazonaws.com/jhsong-devops-nginx:0.2
    imagePullPolicy: Always
    ports:
      - containerPort: 80
  - name: flask
    image: 574261620507.dkr.ecr.us-east-1.amazonaws.com/jhsong-devops-flask:0.2
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
  imagePullSecrets:
    - name: devops-ecr-registry
