apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: 574261620507.dkr.ecr.us-east-1.amazonaws.com/jhsong-devops-nginx:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: flask
          image: 574261620507.dkr.ecr.us-east-1.amazonaws.com/jhsong-devops-flask:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
